#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Sat May 26 11:26:34 IST 2018
apiSecret=a203b2a5811080ca3f4096d9489882a8e720eaab23b37b88ae913144ad5fc5d8
